name: CI

on:
  pull_request:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  TF_VERSION: "1.9.5"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: fmt check
        run: terraform -chdir=infra/terraform fmt -check -recursive

      - name: prod init (no backend)
        run: terraform -chdir=infra/terraform/envs/prod init -backend=false

      - name: prod validate
        run: terraform -chdir=infra/terraform/envs/prod validate

      - name: local init (no backend)
        run: terraform -chdir=infra/terraform/envs/local init -backend=false

      - name: local validate
        run: terraform -chdir=infra/terraform/envs/local validate
